import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: '#1a73e8',
          50: '#f0f6ff',
          100: '#d3e3fd',
          200: '#a8c7fa',
          300: '#7cabf6',
          400: '#4f8ff0',
          500: '#1a73e8',
          600: '#1967d2',
          700: '#185abc',
          800: '#174ea6',
          900: '#0b3d91',
        },
        m3: {
          primary: 'var(--m3-primary)',
          'primary-hover': 'var(--m3-primary-hover)',
          'on-primary': 'var(--m3-on-primary)',
          'primary-container': 'var(--m3-primary-container)',
          'on-primary-container': 'var(--m3-on-primary-container)',
          secondary: 'var(--m3-secondary)',
          'secondary-container': 'var(--m3-secondary-container)',
          'on-secondary-container': 'var(--m3-on-secondary-container)',
          red: 'var(--m3-red)',
          'red-container': 'var(--m3-red-container)',
          yellow: 'var(--m3-yellow)',
          'yellow-container': 'var(--m3-yellow-container)',
          green: 'var(--m3-green)',
          'green-container': 'var(--m3-green-container)',
          surface: 'var(--m3-surface)',
          'surface-dim': 'var(--m3-surface-dim)',
          'surface-low': 'var(--m3-surface-container-low)',
          'surface-container': 'var(--m3-surface-container)',
          'surface-high': 'var(--m3-surface-container-high)',
          'surface-highest': 'var(--m3-surface-container-highest)',
          ink: 'var(--m3-on-surface)',
          'ink-variant': 'var(--m3-on-surface-variant)',
          'ink-muted': 'var(--m3-on-surface-muted)',
          'ink-faint': 'var(--m3-on-surface-faint)',
          outline: 'var(--m3-outline)',
          'outline-variant': 'var(--m3-outline-variant)',
        },
        google: {
          blue: '#1a73e8',
          red: '#ea4335',
          yellow: '#fbbc05',
          green: '#34a853',
          grey: '#5f6368',
          'border-light': '#dadce0',
          'bg-light': '#f8f9fa',
        },
      },
      fontFamily: {
        display: ['var(--font-display)', 'Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        sans: ['var(--font-sans)', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        xxl: '1.75rem',
      },
      boxShadow: {
        'elev-1': 'var(--elev-1)',
        'elev-2': 'var(--elev-2)',
        'elev-3': 'var(--elev-3)',
        'elev-4': 'var(--elev-4)',
        'elev-5': 'var(--elev-5)',
      },
      transitionTimingFunction: {
        emphasized: 'cubic-bezier(0.2, 0, 0, 1)',
        standard: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
} satisfies Config;
